FROM ruby:3.4.8

# 必要なOSパッケージ
RUN apt-get update -qq && apt-get install -y \
  build-essential \
  libpq-dev \
  nodejs \
  npm \
  && npm install -g yarn \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/*


WORKDIR /app

# bundler
RUN gem install bundler
